/**
* reaction_wheel_test.ino
*
* BLDC motor control via MCF8315C motor driver + AS5600 magnetic encoder.
* Both devices share the same I2C bus on the STM32 Nucleo G474RE.
*
* Hardware:
* MCF8315C — TI BLDC motor driver, I2C addr 0x5A (set by TI GUI)
* AS5600 — Magnetic rotary encoder, I2C addr 0x36 (fixed)
*
* Motor specs:
* 12V rated, 2600 RPM @ 12V, 7 pole pairs, 220 KV, delta-wound
* Phase R = 2.3Ω, Phase L = 0.86mH, max current = 1A
*
* Speed commands (% of MAX_SPEED configured in CLOSED_LOOP4):
* 0x86660000 = ~5% = ~780 RPM
* 0x8CCC0000 = ~10% = ~1560 RPM
* 0x93330000 = ~15% = ~2340 RPM
* 0x95C20000 = ~17% = ~2600 RPM (rated)
* NOTE: Do not exceed ~17% — MAX_SPEED in CLOSED_LOOP4 is set too high
* by the TI GUI (15583 RPM). Fix: change 0x008E to 0x5FD7C12F [DOESN'T WORK IDK WHY].
*
* Direction (no EEPROM burn needed, takes effect immediately):
* setDirectionCW() — clockwise
* setDirectionCCW() — counter-clockwise
*/

#include <Wire.h>

// ── I2C Addresses ──────────────────────────────────────────────────────────
#define MCF8315_I2C_ADDR  0x5A   // Set by TI GUI (was 0x01)
#define AS5600_I2C_ADDR   0x36   // Fixed, not configurable

// ── Timing ─────────────────────────────────────────────────────────────────
#define DELAY_US_BETWEEN_BYTES 100

// ── Speed Command ──────────────────────────────────────────────────────────
// Format: bit31=OVERRIDE(1), bits30:16=DIGITAL_SPEED_CTRL (0–32767)
// Speed % = DIGITAL_SPEED_CTRL / 32767 * 100
uint32_t targetSpeed = 0x93330000;  // ~15% = ~2340 RPM


// ═══════════════════════════════════════════════════════════════════════════
// SETUP — configure motor driver registers and burn to EEPROM
// ═══════════════════════════════════════════════════════════════════════════
void setup() {
  Wire.begin();
  Serial.begin(115200);
  delay(5000);
  Serial.println("Writing shadow registers...");

  // === Configuration Registers (generated by TI Motor Driver GUI) ===
  writeRegister32(0x0084, 0x0B260340); // MOTOR_STARTUP1  
  writeRegister32(0x0086, 0x0B836004); // MOTOR_STARTUP2 
  writeRegister32(0x0088, 0x104187B8); // CLOSED_LOOP1    
  writeRegister32(0x008A, 0x0BACCCA9); // CLOSED_LOOP2    
  writeRegister32(0x008C, 0x22E15804); // CLOSED_LOOP3    
  writeRegister32(0x008E, 0x5FD7C71A); // CLOSED_LOOP4    
  writeRegister32(0x0090, 0x1A202087); // FAULT_CONFIG1   
  writeRegister32(0x0092, 0x75482340); // FAULT_CONFIG2   
  writeRegister32(0x00A4, 0x08000309); // PIN_CONFIG      
  writeRegister32(0x00A6, 0x05A00001); // DEVICE_CONFIG1  
  writeRegister32(0x00A8, 0x83E8F007); // DEVICE_CONFIG2  
  writeRegister32(0x00AA, 0x41CC5C00); // PERI_CONFIG1    (default CW direction)
  writeRegister32(0x00AC, 0x0C041100); // GD_CONFIG1      
  writeRegister32(0x00AE, 0x01840000); // GD_CONFIG2      
  writeRegister32(0x00A0, 0x09448005); // INT_ALGO_1      
  writeRegister32(0x00A2, 0x000001E0); // INT_ALGO_2      

  // Set Direction  
  // setDirectionCCW();

  Serial.println("Finish write in shadow now.");

  // === Trigger EEPROM Storage ===
  writeRegister32(0x0000EA, 0x8A500000); // EEPROM_PROG_TRIG
  delay(300); // Wait >300ms to allow EEPROM programming

  Serial.println("MCF8315C configured and EEPROM programmed.");

  Wire.end();
}


// ═══════════════════════════════════════════════════════════════════════════
// LOOP — send speed command and stream angle/RPM from encoder
// ═══════════════════════════════════════════════════════════════════════════

void loop() {
  Wire.begin();
  Serial.begin(115200);
  delay(20000);

  writeRegister32(0x00EC, targetSpeed); // MOTOR_STARTUP1; set speed
  Serial.print("Speed command sent: 0x"); Serial.println(targetSpeed, HEX);

  if (!as5600MagnetDetected()) {
    Serial.println("AS5600: No magnet detected — check alignment and airgap (0.5-3mm).");
    return;
  }

  /* Print Angle and RPM of Motor TEST */
  unsigned long lastPrint = 0;
  while (true) {
    float rpm = as5600GetRPM();
    unsigned long now = millis();
    if (now - lastPrint >= 100) { // Sample RPM every 100ms
      Serial.print("Angle: "); Serial.print(as5600GetAngle());
      Serial.print("  RPM: "); Serial.println(rpm, 1);
      lastPrint = now;
    }
  }

  // // READ REGISTER TEST
  // uint32_t motor_driver_read = readRegister32(0x00EC);
  // uint16_t hall_read = as5600ReadByte(0x0B);

  // Serial.print("Register 0xEC print: ");
  // Serial.println(motor_driver_read, HEX);

  // Serial.print("Speed (for ref): ");
  // Serial.println(targetSpeed, HEX);
  // //

  delay(2000); // Wait >300ms to allow EEPROM programming
}


// ═══════════════════════════════════════════════════════════════════════════
// MCF8315C — Motor Driver Helpers
// ═══════════════════════════════════════════════════════════════════════════

// 3-byte control header + 4-byte little-endian data.
// ctrl[0]=0x10: write, no CRC, 32-bit, page 0
void writeRegister32(uint16_t address, uint32_t data) {
  Wire.beginTransmission(MCF8315_I2C_ADDR);

  // I2C Header: [control][memory address]
  uint8_t ctrl[3];
  ctrl[0] = 0x10;             // OP_R/W=0 (write), CRC=0, DLEN=01 (32-bit), MEM_SEC=0
  ctrl[1] = 0x00;             // MEM_PAGE=0, 0x0 for adress beginning
  ctrl[2] = address & 0xFF;   // EEPROM register offset
  // target_ID already sent by wire.write
  Wire.write(ctrl[0]);
  delayMicroseconds(DELAY_US_BETWEEN_BYTES);
  Wire.write(ctrl[1]);
  delayMicroseconds(DELAY_US_BETWEEN_BYTES);
  Wire.write(ctrl[2]);
  delayMicroseconds(DELAY_US_BETWEEN_BYTES);

  // Write 32-bit little-endian data
  Wire.write((uint8_t)(data & 0xFF));
  delayMicroseconds(DELAY_US_BETWEEN_BYTES);
  Wire.write((uint8_t)((data >> 8) & 0xFF));
  delayMicroseconds(DELAY_US_BETWEEN_BYTES);
  Wire.write((uint8_t)((data >> 16) & 0xFF));
  delayMicroseconds(DELAY_US_BETWEEN_BYTES);
  Wire.write((uint8_t)((data >> 24) & 0xFF));
  delayMicroseconds(DELAY_US_BETWEEN_BYTES);

  uint8_t result = Wire.endTransmission();
  if (result != 0) {
    Serial.print("I2C write error at 0x");
    Serial.print(address, HEX);
    Serial.print(" → error code: ");
    Serial.println(result);
  } else {
    Serial.print("Write OK to 0x");
    Serial.println(address, HEX);
  }
}

// 3-byte control header with repeated start, then read 4 bytes little-endian.
// ctrl[0]=0x90: read, no CRC, 32-bit. Returns 0xFFFFFFFF on failure.
uint32_t readRegister32(uint16_t address) {
  // === Phase 1: Send control word (who to read from) ===
  Wire.beginTransmission(MCF8315_I2C_ADDR);

  Wire.write(0x90);                  // OP_R/W=1 (read), CRC=0, DLEN=01 (32-bit), MEM_SEC=0
  delayMicroseconds(DELAY_US_BETWEEN_BYTES);
  Wire.write(0x00);                  // MEM_PAGE=0
  delayMicroseconds(DELAY_US_BETWEEN_BYTES);
  Wire.write(address & 0xFF);        // register offset
  delayMicroseconds(DELAY_US_BETWEEN_BYTES);

  // false = repeated start (no stop condition), required by MCF8315C read protocol
  uint8_t result = Wire.endTransmission(false);
  if (result != 0) {
    Serial.print("I2C read setup error at 0x");
    Serial.print(address, HEX);
    Serial.print(" -> code: ");
    Serial.println(result);
    return 0xFFFFFFFF; // sentinel value indicating failure
  }

  // === Phase 2: Repeated Start, read 4 bytes back ===
  uint8_t received = Wire.requestFrom((uint8_t)MCF8315_I2C_ADDR, (uint8_t)4);
  if (received != 4) {
    Serial.print("I2C read incomplete at 0x");
    Serial.print(address, HEX);
    Serial.print(" got ");
    Serial.print(received);
    Serial.println(" bytes");
    return 0xFFFFFFFF;
  }

  // LSB first, same as write
  uint32_t val = 0;
  val |= ((uint32_t)Wire.read());        // byte 0 - LSB
  val |= ((uint32_t)Wire.read()) << 8;   // byte 1
  val |= ((uint32_t)Wire.read()) << 16;  // byte 2
  val |= ((uint32_t)Wire.read()) << 24;  // byte 3 - MSB

  return val;
}

// Direction control - PERI_CONFIG1 shadow write
// DIR_INPUT bits [20:19]: 01=CW, 10=CCW
void setDirectionCW() {
  writeRegister32(0x00AA, 0x41CC5C00); // DIR_INPUT=1, clockwise
}
void setDirectionCCW() {
  writeRegister32(0x00AA, 0x41D45C00); // DIR_INPUT=2, counter-clockwise
}


// ═══════════════════════════════════════════════════════════════════════════
// AS5600 — Magnetic Encoder Helpers
// ═══════════════════════════════════════════════════════════════════════════

// Read 1-byte register from AS5600
uint8_t as5600ReadByte(uint8_t reg) {
  Wire.beginTransmission(AS5600_I2C_ADDR);
  Wire.write(reg);
  Wire.endTransmission(false);        // repeated start, per datasheet Figure 20
  Wire.requestFrom((uint8_t)AS5600_I2C_ADDR, (uint8_t)1);
  uint8_t val = 0;
  if (Wire.available()) val |= Wire.read();
  return val;
}

// Read 2-byte register from AS5600, big-endian (MSB first) — opposite to MCF8315C.
uint16_t as5600ReadWord(uint8_t reg) {
  Wire.beginTransmission(AS5600_I2C_ADDR);
  Wire.write(reg);
  Wire.endTransmission(false);        // repeated start, per datasheet Figure 20
  Wire.requestFrom((uint8_t)AS5600_I2C_ADDR, (uint8_t)2);
  uint16_t val = 0;
  if (Wire.available()) val  = (uint16_t)Wire.read() << 8; // MSB first
  if (Wire.available()) val |= Wire.read();                 // then LSB
  return val;
}


// STATUS reg 0x0B: bit5=MD (detected), bit4=ML (too weak), bit3=MH (too strong).
// Requires diametric magnet, centered over chip, airgap 0.5–3mm.
bool as5600MagnetDetected() {
  uint8_t status = as5600ReadByte(0x0B); // reads STATUS register on AS5600
  if ((status >> 4) & 1) Serial.println("AS5600: Magnet too weak — move closer.");
  if ((status >> 3) & 1) Serial.println("AS5600: Magnet too strong — increase airgap.");
  return ((status >> 5) & 1) && !((status >> 4) & 1) && !((status >> 3) & 1);
}

// ANGLE register 0x0E–0x0F, 12-bit big-endian. 0–4095 = 0–360°. (0.0879°/count)
uint16_t as5600GetAngle() {
  return as5600ReadWord(0x0E) & 0x0FFF; // mask to 12 bits
}

// RPM from angle delta over time. Call every ~100ms for stable readings.
// Positive = CW, negative = CCW. Handles 0↔4095 wrap-around.
float as5600GetRPM() {
  static uint16_t lastAngle = 0;
  static unsigned long lastTime = 0;

  uint16_t currentAngle = as5600GetAngle();
  unsigned long now = micros();

  // Handle wrap-around: 4095->0 (forward) or 0->4095 (backward)
  int16_t delta = (int16_t)currentAngle - (int16_t)lastAngle;
  if (delta >  2048) delta -= 4096; // wrapped CCW
  if (delta < -2048) delta += 4096; // wrapped CW

  unsigned long elapsed = now - lastTime; // microseconds

  lastAngle = currentAngle;
  lastTime = now;

  if (elapsed == 0) return 0;

  // (delta ticks / 4096 ticks per rev) / (elapsed us / 1,000,000) * 60 = RPM
  return ((float)delta / 4096.0f) / ((float)elapsed / 1000000.0f) * 60.0f;
}
